In [1]:
# control random processes
import torch
torch.manual_seed(1)
import numpy as np
np.random.seed(1)

In [2]:
from network import NeuralNetwork

In [3]:
for move_penalty in [None,'nonzero','linear_move_num','exponential_move_num']:
    for game_penalty in ['scores','max','log2_max','tile_sums']:
        network = NeuralNetwork()
        network.train(duration=1, move_penalty_type=move_penalty,
                     game_penalty_type=game_penalty)

[[ 16   2]
 [ 32  37]
 [ 64 282]
 [128 782]
 [256 766]
 [512 131]]
[[ 16   1]
 [ 32  23]
 [ 64 242]
 [128 776]
 [256 885]
 [512  73]]
[[ 32  14]
 [ 64 170]
 [128 803]
 [256 903]
 [512 110]]
[[  8   1]
 [ 16  17]
 [ 32 128]
 [ 64 571]
 [128 842]
 [256 405]
 [512  36]]
[[ 32  49]
 [ 64 269]
 [128 870]
 [256 747]
 [512  65]]
[[ 32  13]
 [ 64 171]
 [128 788]
 [256 937]
 [512  91]]
[[ 32  14]
 [ 64 190]
 [128 795]
 [256 895]
 [512 106]]
[[ 16   1]
 [ 32  52]
 [ 64 239]
 [128 634]
 [256 947]
 [512 127]]
[[ 16   1]
 [ 32   7]
 [ 64 183]
 [128 764]
 [256 967]
 [512  78]]
[[  8   4]
 [ 16 117]
 [ 32 540]
 [ 64 858]
 [128 439]
 [256  41]
 [512   1]]
[[ 32  18]
 [ 64 173]
 [128 739]
 [256 948]
 [512 122]]
[[ 32  30]
 [ 64 263]
 [128 789]
 [256 811]
 [512 107]]
[[ 16  20]
 [ 32 108]
 [ 64 409]
 [128 816]
 [256 598]
 [512  49]]
[[ 16   4]
 [ 32  40]
 [ 64 272]
 [128 763]
 [256 867]
 [512  54]]
[[ 32  34]
 [ 64 291]
 [128 791]
 [256 797]
 [512  87]]
[[  16    1]
 [  32   45]
 [  64  241]
 [ 128  634

In [ ]:
import pandas as pd
# mini-iterative, random_games=True, 5 hours
baseline = pd.DataFrame([[ 16,   0],
 [  32,   32],
 [  64,  351],
 [ 128, 1020],
 [ 256,  556],
 [ 512,   41]])



after = pd.DataFrame([[ 16,   1],
 [ 32,  20],
 [ 64, 236],
 [128, 758],
 [256, 910],
 [512,  75]])

import matplotlib.pyplot as plt

fig, (ax1, ax2) = plt.subplots(2,1, sharex=True, sharey=True)

ax1.bar(baseline[0].astype(str), before[1])
ax1.set_ylabel('Before')

ax2.bar(after[0].astype(str), after[1])
ax2.set_ylabel('After')

fig.suptitle('Number of games reaching tile value,\nbefore and after training')

fig.show()

In [ ]:
params = {'random_games':[False, True],
         'random_frac':[None, np.random.uniform(0, 1)],
         'batch_size':10,
          'lr':0.001,
         'move_penalty_type':[None,'nonzero','linear_move_num','exponential_move_num'],
         'game_penalty_type':['scores','max','log2_max','tile_sums']}

In [ ]:
# test parameter combinations

for game_type in params['game_type']:
    for random_games in params['random_games']:
        for random_frac in params['random_frac']:
            for move_penalty_type in params['move_penalty_type']:
                for game_penalty_type in params['game_penalty_type']:
                    network.train(test=True, duration=1/60000,
                                 game_type=game_type, random_games=random_games, random_frac=random_frac,
                                 move_penalty_type=move_penalty_type, game_penalty_type=game_penalty_type)